theme: jekyll-theme-minimal
title: Susanna Weber
description: Columbia University Biomedical Engineering Doctoral Student
logo: /assets/headshot.png
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: false
google_analytics: G-H4T97QBFMQ
markdown: kramdown
permalink: pretty
