theme: jekyll-theme-minimal
title: Susanna Weber
description: Columbia University | BME Ph.D. Student
logo: /assets/headshot.png
show_downloads: false
google_analytics: G-H4T97QBFMQ
markdown: kramdown
permalink: pretty
